USE [master]
GO

/****** Object:  Database [MyShop]    Script Date: 15.03.2023 20:45:58 ******/
CREATE DATABASE [MyShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyShop', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\MyShop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyShop_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\MyShop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MyShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MyShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyShop] SET RECOVERY FULL 
GO

ALTER DATABASE [MyShop] SET  MULTI_USER 
GO

ALTER DATABASE [MyShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MyShop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MyShop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MyShop] SET QUERY_STORE = ON
GO

ALTER DATABASE [MyShop] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [MyShop] SET  READ_WRITE 
GO


